apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "zmon-test"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        application: "zmon-test"
        version: "1.0"
        release: "1"
        stage: "test"
    spec:
      containers:
        - name: "zmon-controller"
          image: "pierone.stups.zalan.do/mentoring/zmon-controller-ot:1.3"
          env:
            - name: MEM_JAVA_PERCENT
              value: "25"
            - name: SERVER_COMPRESSION_ENABLED
              value: "true"
            - name: ZMON_TEAMS_SIMPLE_DEFAULT_TEAM
              value: "ZMON"
            - name: ZMON_SIGNUP_GITHUB_ALLOWED_USERS
              value: "*"
            - name: ZMON_SIGNUP_GITHUB_ALLOWED_ORGAS
              value: "*"
            - name: ZMON_OAUTH2_SSO_CLIENT_ID
              value: "344c9a90fc697fe6662a"
            - name: ZMON_OAUTH2_SSO_CLIENT_SECRET
              value: "a2bbb03a29f6737af04c77f2d88e8f8199ff179b"
            - name: ZMON_AUTHORITIES_SIMPLE_ADMINS
              value: "*"
            - name: ZMON_KAIROSDB_URL
              value: http://kairosdb:8083/
            - name: SERVER_COMPRESSION_MIME_TYPES
              value: application/json,application/javascript,application/xml,text/html,text/xml,text/plain
            - name: ZMON_JWT_SECRET
              value: "DEMO-ONLY-CHANGE-ME-Bgzogya43C3bvV0o"
            - name: PRESHARED_TOKENS_123_UID
              value: "demotoken"
            - name: PRESHARED_TOKENS_123_EXPIRES_AT
              value: "1758021422"
            - name: SPRING_PROFILES_ACTIVE
              value: github
            - name: MANAGEMENT_SECURITY_ENABLED
              value: "false"
            - name: POSTGRES_URL
              value: jdbc:tracing:postgresql://postgres:5432/local_zmon_db
            - name: POSTGRES_USERNAME
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "Uhaf5AekUhaf5Aek"
            - name: MANAGEMENT_PORT
              value: "7979"
            - name: ZMON_SCHEDULER_URL
              value: http://scheduler:8085/
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: ZMON_EVENTLOG_URL
              value: http://eventlog:8081/
            - name: ZMON_KAIROSDB_MAXCONNECTIONSTOTAL
              value: "75"
            - name: JAEGER_SERVICE_NAME
              value: "zmon-controller"
            - name: ZMON_KAIROSDB_URL
              value: "http://kairosdb:8083/"
            - name: SSO_AUTHORIZE_URL
              value: "https://auth.zalando.com/oauth2/authorize"
            - name: SSO_ACCESS_TOKEN_URL
              value: "https://auth.zalando.com/oauth2/access_token?realm=/employees"
            - name: "CREDENTIALS_DIR"
              value: /meta/credentials
            - name: CREDENTIALS_PLATFORM_ENABLED
              value: "true"
            - name: CREDENTIALS_TOKEN_NAME
              value: "zmon"
            - name: TOKENS_ENABLE_MOCK
              value: "false"
            - name: OAUTH2_ACCESS_TOKEN_URL
              value: "https://sandbox.identity.zalando.com/oauth2/token?business_partner_id=810d1d00-4312-43e5-bd31-d8373fdd24c7"
            - name: ZMON_ZAUTH_TEAM_SERVICE_URL
              value: http://users-api-stub
            - name: ZMON_ZAUTH_USER_SERVICE_URL
              value: http://users-api-stub
            - name: SECURITY_OAUTH2_RESOURCE_USERINFOURI
              value: "https://sandbox.identity.zalando.com/oauth2/tokeninfo"
            - name: SPRING_APPLICATION_JSON
              value: |
                {
                  "endpoints": {
                    "cors": {
                      "allowed-origins": "https://zmon-test.mentoring.zalan.do,https://krgr.github.io",
                      "enable-credentials": true
                    }
                  },
                  "zmon": {
                    "oauth2": {
                      "sso": {
                        "platform-token-name": "zmon",
                        "authorize-url": "https://sandbox.identity.zalando.com/oauth2/authorize",
                        "access-token-url": "https://sandbox.identity.zalando.com/oauth2/token",
                        "additional-params": {
                          "business_partner_id": "810d1d00-4312-43e5-bd31-d8373fdd24c7"
                        }
                      }
                    },
                    "kairosdb": {
                      "kairosdbs": [
                        {
                          "name": "kairosdb",
                          "url": "http://kairosdb/",
                          "oauth2": false
                        }
                      ]
                    },
                    "zauth": {
                      "team-extension": {
                        "Moloko": [
                          "Trux"
                        ],
                        "Goya": [
                          "Trux"
                        ]
                      },
                      "team-overlay": {
                        "akoeb": [
                          "reklame",
                          "nuggad"
                        ],
                        "mmaza": [
                          "CEP"
                        ],
                        "cmeise": [
                          "COAST"
                        ],
                        "eiglhaut": [
                          "Pathfinder"
                        ],
                        "mobuchowicz": [
                          "Lounge IT"
                        ],
                        "bjunglas": [
                          "COAST"
                        ],
                        "ohuelscher": [
                          "Zaster"
                        ],
                        "sdastan": [
                          "COAST"
                        ],
                        "npetersohn": [
                          "Paradox"
                        ]
                      }
                    }
                  }
                }

            # JVM memory
            - name: MEM_TOTAL_KB
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory
                  divisor: 1Ki
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              memory: 2Gi
          ports:
            - containerPort: 7979
            - containerPort: 8443
          volumeMounts:
            - name: "zmon-controller"
              mountPath: /meta/credentials
              readOnly: true
      volumes:
      - name: "zmon-controller"
        secret:
          secretName: "zmon-test-credentials"  