version: "2.1"
services:
    postgresql:
        image: postgres:9.6.1
        environment:
            POSTGRES_PASSWORD: Uhaf5AekUhaf5Aek
        ports:
         - "38088:5432"
        volumes:
         - "./postgresql-data:/var/lib/postgresql/data"
        healthcheck:
            test: "psql -c 'SELECT 1' -U postgres"
            interval: 10s
            retries: 99
            timeout: 10s
    postgresql-schemas:
        build: "postgresql-inject/"
        environment:
          POSTGRESQL_PASSWORD: Uhaf5AekUhaf5Aek
        depends_on:
          postgresql:
              condition: "service_healthy"
    cassandra:
        image: cassandra:3.11
        environment:
            JAVA_OPTS: "-Xmx512M"
        ports:
         - "9042:9042"
         - "7199:7199"
        volumes:
         - "./cassandra-data:/var/lib/cassandra" 
        healthcheck:
            test: "bash -c 'nodetool status | grep UN'"
            interval: 15s
            retries: 99
            timeout: 15s
    data-service:
        image: zmon-data-service:ot-1.0
        #image: pierone.stups.zalan.do/zmon/zmon-data-service-unstable:pr-89-1-6ea1f0a
        environment:
            JAVA_OPTS: "-Xmx512M -Dappdynamics.controller.hostName=test-appd.zalando.org -Dappdynamics.controller.port=443 -Dappdynamics.controller.ssl.enabled=true -Dappdynamics.agent.applicationName=zmon -Dappdynamics.agent.tierName=zmon-data-service -Dappdynamics.agent.nodeName=zmon-data-service -Dappdynamics.agent.accountName=customer1 -Dappdynamics.agent.accountAccessKey=9966815f-23ba-4de1-a9fb-19e9a07a49a6"
            DATASERVICE_PROXY_KAIROSDB_URL: http://kairosdb:8083
            DATASERVICE_REDIS_HOST: redis
            #DATASERVICE_REDIS_HOST: a34e6d909c3dc11e7a6b70249bf77341-678114054.eu-central-1.elb.amazonaws.com
            DATASERVICE_REDIS_PORT: 6379
            DATASERVICE_EVENTLOG_URL: http://eventlog:8081/
            TOKENINFO_URL:  https://info.services.auth.zalando.com/oauth2/tokeninfo?access_token=
            OPENTRACING_LIGHTSTEP_COLLECTOR_HOST: "tracing.zmon.zalan.do"
            OPENTRACING_LIGHTSTEP_COLLECTOR_PORT: 8445
            OPENTRACING_LIGHTSTEP_ACCESS_TOKEN: "b34a7e251d37e888e0daf472ac5362b8"
            OPENTRACING_LIGHTSTEP_COMPONENT_NAME: "data-service-vibs"
            OPENTRACING_TRACER: "lightstep"
            SPRING_APPLICATION_JSON: |
              {"dataservice": {
                "data_points_store_properties": {
                    "enabled": true,
                    "host": "redis"
                }
              }}
        ports:
         - "8086:8086"
    redis:
        image: registry.opensource.zalan.do/stups/redis:3.2.0-alpine
        ports:
         - "38086:6379"
    kairosdb:
        #image: pierone.stups.zalan.do/zmon/kairosdb-unstable:pr-54-5-test
        image: pierone.stups.zalan.do/zmon/kairosdb-unstable:pr-54-10-test2 
        #image: kairosdb:ot-1.0 
        environment:
            KAIROSDB_JETTY_PORT: 8083
            KAIROSDB_DATASTORE_CASSANDRA_HOST_LIST: cassandra
            KAIROSDB_DATASTORE_CASSANDRA_DATAPOINT_TTL: 864000
            JAEGER_SERVICE_NAME: "zmon-kairosdb"
            JAEGER_AGENT_HOST: "jaeger"
            JAEGER_AGENT_PORT: 5775
            JAEGER_REPORTER_LOG_SPANS: "true"
            JAEGER_REPORTER_MAX_QUEUE_SIZE: 100
            JAEGER_TAGS: "opentracing=poc"
            JAEGER_REPORTER_FLUSH_INTERVAL: 100
            JAEGER_SAMPLER_TYPE: "probabilistic"
            JAEGER_SAMPLER_PARAM: 1
            OPENTRACING_LIGHTSTEP_COLLECTOR_HOST: "tracing.zmon.zalan.do"
            OPENTRACING_LIGHTSTEP_COLLECTOR_PORT: 8445
            OPENTRACING_LIGHTSTEP_ACCESS_TOKEN: "b34a7e251d37e888e0daf472ac5362b8"
            OPENTRACING_LIGHTSTEP_COMPONENT_NAME: "kairosdb_local_vibs"
            OPENTRACING_TRACER: "lightstep"
        depends_on:
          cassandra:
            condition: "service_healthy"
        ports:
         - "38083:8083"
         - "5775:5775"
    eventlog:
        image: pierone.stups.zalan.do/mentoring/zmon-eventlog-service:ot 
        environment:
            MEM_JAVA_PERCENT: 10
            POSTGRESQL_HOST: postgresql
            POSTGRESQL_DATABASE: local_zmon_db
            POSTGRESQL_USER: postgres
            POSTGRESQL_PASSWORD: Uhaf5AekUhaf5Aek
            JAEGER_SERVICE_NAME: "zmon-eventlog"
            JAEGER_AGENT_HOST: "jaeger"
            JAEGER_AGENT_PORT: 5775
            JAEGER_REPORTER_LOG_SPANS: "true"
            JAEGER_REPORTER_MAX_QUEUE_SIZE: 100
            JAEGER_TAGS: "opentracing=poc"
            JAEGER_REPORTER_FLUSH_INTERVAL: 100
            JAEGER_SAMPLER_TYPE: "probabilistic"
            JAEGER_SAMPLER_PARAM: 1
        depends_on:
            - "postgresql"
    controller:
        #image: zmon-controller:ot-1.0 
        image: pierone.stups.zalan.do/zmon/zmon-controller:v346-zv1
        environment:
          MEM_JAVA_PERCENT: 25
          MANAGEMENT_PORT: 7979
          MANAGEMENT_SECURITY_ENABLED: "false"
          SPRING_PROFILES_ACTIVE: github
          ZMON_TEAMS_SIMPLE_DEFAULT_TEAM: ZMON
          ZMON_SIGNUP_GITHUB_ALLOWED_USERS: "*"
          ZMON_SIGNUP_GITHUB_ALLOWED_ORGAS: "*"
          ZMON_OAUTH2_SSO_CLIENT_ID: 344c9a90fc697fe6662a
          ZMON_OAUTH2_SSO_CLIENT_SECRET: a2bbb03a29f6737af04c77f2d88e8f8199ff179b
          ZMON_AUTHORITIES_SIMPLE_ADMINS: "*"
          POSTGRES_URL: jdbc:postgresql://postgresql:5432/local_zmon_db
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: Uhaf5AekUhaf5Aek
          REDIS_HOST: redis
          REDIS_PORT: 6379
          ZMON_KAIROSDB_URL: http://kairosdb:8083/
          ZMON_SCHEDULER_URL: http://scheduler:8085/
          ZMON_EVENTLOG_URL: http://eventlog:8081/
          ZMON_JWT_SECRET: DEMO-ONLY-CHANGE-ME-Bgzogya43C3bvV0o
          PRESHARED_TOKENS_123_UID: demotoken
          PRESHARED_TOKENS_123_EXPIRES_AT: 1758021422
          #SPRING_APPLICATION_JSON: '{"server":{"ssl":{"key-store-type":"jks","key-store":"classpath:host-controller.jks","key-alias":"controller"}}}'
          JAEGER_SERVICE_NAME: "zmon-controller"
          JAEGER_SERVICE_NAME: "zmon-controller"
          JAEGER_AGENT_HOST: "jaeger"
          JAEGER_AGENT_PORT: 5775
          JAEGER_REPORTER_LOG_SPANS: "true"
          JAEGER_REPORTER_MAX_QUEUE_SIZE: 100
          JAEGER_TAGS: "opentracing=poc"
          JAEGER_REPORTER_FLUSH_INTERVAL: 100
          JAEGER_SAMPLER_TYPE: "probabilistic"
          JAEGER_SAMPLER_PARAM: 1
          ZMON_NOTIFICATIONSERVICE_URL: "http://notification"
          SSO_AUTHORIZE_URL: "https://auth.zalando.com/oauth2/authorize"
          SSO_ACCESS_TOKEN_URL: "https://auth.zalando.com/oauth2/access_token?realm=/employees"
          TRACER_LIGHTSTEP_ENABLED: "true"
          TRACER_COMPONENT_NAME: "local_controller_grpc"
          TRACER_COLLECTOR_HOST: "lightstep-collector-grpc.stups-test.zalan.do"
          TRACER_COLLECTOR_PORT: 443
          TRACER_ACCESS_TOKEN: "b34a7e251d37e888e0daf472ac5362b8"
          #OPENTRACING_LIGHTSTEP_HOST: "lightstep-collector-grpc.stups-test.zalan.do"
          OPENTRACING_LIGHTSTEP_HOST: "tracing.zmon.zalan.do"
          OPENTRACING_LIGHTSTEP_PORT: 8445
          OPENTRACING_LIGHTSTEP_ACCESS_TOKEN: "b34a7e251d37e888e0daf472ac5362b8"
          OPENTRACING_LIGHTSTEP_SERVICE_NAME: "zmon_local_vibs"
          OPENTRACING_LIGHTSTEP_EUM_HOST: "tracing.zmon.zalan.do"
          OPENTRACING_LIGHTSTEP_EUM_PORT: 8443
          OPENTRACING_LIGHTSTEP_EUM_SERVICE_NAME: "zmon-controller-ui"
          OPENTRACING_LIGHTSTEP_EUM_VERBOSITY: 1
          OPENTRACING_LIGHTSTEP_EUM_XHR: "true"
          OPENTRACING_PROVIDER: "lightstep"
        ports:
         - "38080:8080"
         - "8443:8443"
         - "7979:7979"
        depends_on:
            - "redis"
            - "postgresql"
            - "jaeger"
    jaeger:
        image: jaegertracing/all-in-one:latest
        ports:
         - "16686:16686"
    scheduler:
        #image: scheduler:1.0
        image: pierone.stups.zalan.do/zmon/zmon-scheduler:v46-zv148
        environment:
          MEM_JAVA_PERCENT: 20
          JAVA_OPTS: "-Djavax.net.ssl.trustStorePassword=mypassword -Djavax.net.ssl.trustStore=/resources/host-controller.jks"
          SCHEDULER_URLS_WITHOUT_REST: "true"
          SCHEDULER_ENTITY_SERVICE_URL: https://controller:8443/
          SCHEDULER_OAUTH2_STATIC_TOKEN: "123"
          SCHEDULER_CONTROLLER_URL: https://controller:8443/
          SCHEDULER_REDIS_HOST: redis
          JAEGER_SERVICE_NAME: "zmon-scheduler"
          JAEGER_AGENT_HOST: "jaeger"
          JAEGER_AGENT_PORT: 5775
          JAEGER_REPORTER_LOG_SPANS: "true"
          JAEGER_REPORTER_MAX_QUEUE_SIZE: 100
          JAEGER_TAGS: "opentracing=poc"
          JAEGER_REPORTER_FLUSH_INTERVAL: 100
          JAEGER_SAMPLER_TYPE: "probabilistic"
          JAEGER_SAMPLER_PARAM: 1
          OPENTRACING_LIGHTSTEP_HOST: "tracing.zmon.zalan.do"
          OPENTRACING_LIGHTSTEP_PORT: 8445
          OPENTRACING_LIGHTSTEP_ACCESS_TOKEN: "b34a7e251d37e888e0daf472ac5362b8"
          OPENTRACING_LIGHTSTEP_SERVICE_NAME: "scheduler_local_vibs"
          OPENTRACING_LIGHTSTEP_EUM_HOST: "tracing.zmon.zalan.do"
          OPENTRACING_LIGHTSTEP_EUM_PORT: 8443
          OPENTRACING_PROVIDER: "lightstep"
          ZMON_BASE_URL: "http://data-service:8086"
          LOCAL_ENTITY_ID: ""
          SCHEDULER_ENTITY_SKIP_ON_FIELD: ""
          SCHEDULER_ENABLE_GLOBAL_ENTITY: "true"
        ports:
        - "38079:8085"
        volumes:
            - "./resources:/resources"
    worker:
        image: registry.opensource.zalan.do/stups/zmon-worker:v130
        #image: zmon-worker:1.0
        ports:
         - "9000:8080"
        environment:
          WORKER_REDIS_SERVERS: redis:6379
          #WORKER_KAIROSDB_HOST: kairosdb
          ZMON_WORKER_WORKER_DATASERVICE_URL: "http://data-service:8086/api/v1/data/"
          WORKER_WORKER_DATASERVICE_URL: "http://data-service:8086/api/v1/data/"
          OAUTH2_ACCESS_TOKEN_URL: "https://token.services.auth.zalando.com/oauth2/access_token?realm=/services"
          WORKER_EVENTLOG_HOST: eventlog
          WORKER_EVENTLOG_PORT: 8081
          JAEGER_SERVICE_NAME: "zmon-worker"
          JAEGER_AGENT_HOST: "jaeger"
          JAEGER_AGENT_PORT: 5775
          JAEGER_REPORTER_LOG_SPANS: "true"
          JAEGER_REPORTER_MAX_QUEUE_SIZE: 100
          JAEGER_TAGS: "opentracing=poc"
    #notification:
    #    image: zmon-notification-service-ot:1.0
    #    environment:
    #      NOTIFICATIONS_EVENTLOG_URL: "http://eventlog:8081"
    #      NOTIFICATIONS_EVENTLOG_URL: "true"
    #      NOTIFICATIONS_ZMON_URL: "http://controller:8443/"
    #      NOTIFICATIONS_REDIS_URI: "redis://a34e6d909c3dc11e7a6b70249bf77341-678114054.eu-central-1.elb.amazonaws.com:6379/0"
    #      JAEGER_SERVICE_NAME: "zmon-notification-service"
    #      JAEGER_AGENT_HOST: "jaeger"
    #      JAEGER_AGENT_PORT: 5775
    #      JAEGER_REPORTER_LOG_SPANS: "true"
    #      JAEGER_REPORTER_MAX_QUEUE_SIZE: 100
    #      JAEGER_TAGS: "opentracing=poc"
    #      JAEGER_REPORTER_FLUSH_INTERVAL: 100
    #      JAEGER_SAMPLER_TYPE: "probabilistic"
    #      JAEGER_SAMPLER_PARAM: 1
    #      SERVER_PORT: 9090
    datapoints-consumer:
        #image: pierone.stups.zalan.do/eagleeye/zmon-datapoints-consumer:r13
        #image: pierone.stups.zalan.do/eagleeye/zmon-datapoints-consumer-test:pr-20-14
        image: datapoints-consumer:ot-1.0
        environment:
          REDIS_HOST: redis 
          KAIROSDB_URLS: http://kairosdb:8083/api/v1/datapoints
          NUM_WORKERS: 42
          LIGHTSTEP_TOKEN: "b34a7e251d37e888e0daf472ac5362b8"
          LIGHTSTEP_COLLECTOR: "tracing.zmon.zalan.do"
